apiVersion: v1
kind: Namespace
metadata:
  name: data-platform

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: data-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: sonusukralia/miniod:3.5
        args:
        - server
        - /data
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      volumes:
      - name: minio-storage
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: data-platform
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: minio
