apiVersion: v1
kind: Service
metadata:
  name: dremio-service
  namespace: data-platform
spec:
  selector:
    app: dremio
  ports:
    - protocol: TCP
      port: 9047
      targetPort: 9047
      name: http
    - protocol: TCP
      port: 31010
      targetPort: 31010
      name: odbc-jdbc
    - protocol: TCP
      port: 45678
      targetPort: 45678
      name: internal
  type: LoadBalancer
